name: fasum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.7.10
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  geolocator: ^12.0.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  http: ^1.4.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fasum_icon_512.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/fasum_icon.png
    - assets/fasum_icon.png
